### ISSUE TITLE
Unable to update height info in Helium app

### ISSUE THREAD

**Issue by dknightcc11** [helium/hotspot-app#1083]
**Describe the bug**
I am unable to update my height info for my miner Rak HotSpotv2. It's 18m AGL but the Helium app won't let me update it.

**To Reproduce**
I click on the gear icon
I click on "Update Hotspot"
I enter my new height info and when I submit, the page goes blank and hangs there.

I have attached a screen recording for reference,

**Expected behavior**
I should be able to update my height info,

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro Max
- OS: iOS 15.1
- App Version: Latest

**Additional context**
Please see attached screen recording. Thank you.

https://user-images.githubusercontent.com/46775664/141655455-e4bd3df8-cdd8-4cf4-ba88-47a2d65fc3a3.mov

.

**Comment by gitemre** [comment]
Have you tried selecting your antenna?

**Comment by jbuecker** [comment]
I have the same exact issue.

**Comment by cokes518** [comment]
@dknightcc11 can you record a video of updating height starting from pressing the settings icon?

**Comment by turribeach** [comment]
I am on iOS 15.1 and I have an iPhone 11 Pro. I spent a week trying to update my antenna gain and height until I was able to figure out what was happening. The issue is that when I try to input the antenna gain and height the keyboard pops up (as expected, see second screen shot below). But crucially the keyboard is covering the Update Antenna button that you need to tap to confirm the update (you can see the button on the first screen shot). So when you tap on Done after you input the data the screen just goes all blur (see third screen shot) but it doesn't actually submit anything. And since the input screen it's gone you can't see the Update Antenna anymore. Also note that the keyboard that pops up doesn't have the Hide Keyboard key so I am unable to hide it to see the Update Antenna button. How did I get around this bug? I installed the app on my iPad and due to the different screen size I was able to finally update my antenna height and gain.

![IMG_3788](https://user-images.githubusercontent.com/34696469/144315584-89d83eb9-b6f9-44af-a697-9f79c15354b2.jpg)

![IMG_3779](https://user-images.githubusercontent.com/34696469/144315221-94ec479f-83ec-4ca3-87ac-438ae759c250.PNG)

![IMG_3780](https://user-images.githubusercontent.com/34696469/144315202-d9ae30f9-cbe9-4324-8a56-1a0aff84da80.PNG)

**Comment by jbuecker** [comment]
TURRIBEACH, well written!!!!, and I also concur this is ABSOLUTELY What I did to solve the issue!  I couldn't even assert a Brand new miner, with the same issue....so I set it up on my iPad, and Everything worked....good catch.... Guys , please fix this.  Thanks! and cheers, JB

**Comment by cokes518** [comment]
this is really helpful. thanks for narrowing it down for us - makes it much easier to fix. we'll be looking at this next.

**Comment by cokes518** [comment]
The latest app update 3.8.5 adds in better logic around closing the keyboard for users to submit the transaction.

**Comment by cokes518** [comment]
Please comment/close if this is fixed for you! thanks for everyone's patience.

**Comment by turribeach** [comment]
Hi, I updated my app to v3.8.5 and I see no improvement at all, it behaves in exactly the same way. Are you sure this is fixed?

**Comment by cokes518** [comment]
> Hi, I updated my app to v3.8.5 and I see no improvement at all, it behaves in exactly the same way. Are you sure this is fixed?

the new app version hides the keyboard when you press "Done". The Update Location card should still be visible. Are you saying that the card is now gone and the only thing you see is the blurred background? what iOS/phone are you using?

**Comment by jbuecker** [comment]
The new version does Not solve the problem.

iOS 15.1.1
iPhone 13 pro

**Comment by turribeach** [comment]
_Are you saying that the card is now gone and the only thing you see is the blurred background? what iOS/phone are you using?_ => Yes, same as before. 

iOS 15.1
iPhone 11 Pro

**Comment by turribeach** [comment]
Are you selecting a Custom Antenna in the Antenna options? I can reproduce it every time. It also happens after I set the antenna dBi and I tap in the Height field.

**Comment by cokes518** [comment]
> Are you selecting a Custom Antenna in the Antenna options? I can reproduce it every time. It also happens after I set the antenna dBi and I tap in the Height field.

can you take a video recording?

**Comment by turribeach** [comment]
https://user-images.githubusercontent.com/34696469/145476574-8f84dc57-cda9-48b2-b93b-bea81e090845.mov

**Comment by cokes518** [comment]
this is awesome. super helpful to understand visually what is happening. will help us narrow it down.

**Comment by turribeach** [comment]
Why is this closed? It is still not fixed in v3.8.5.

**Comment by tyler-whitman** [comment]
> Why is this closed? It is still not fixed in v3.8.5.

We have a fix that will hopefully work for you. It will be out in v3.8.6

**Comment by akavics1** [comment]
I have the same problem since 2021 September :( I was never able to set up a correct Antenna value or height.

**Comment by turribeach** [comment]
> > Why is this closed? It is still not fixed in v3.8.5.
> 
> We have a fix that will hopefully work for you. It will be out in v3.8.6

When is v3.8.6 supposed to be out? Shouldn't this issue be closed once v3.8.6 is out and confirmed as closed?

**Comment by tyler-whitman** [comment]
> > > Why is this closed? It is still not fixed in v3.8.5.
> > 
> > 
> > We have a fix that will hopefully work for you. It will be out in v3.8.6
> 
> When is v3.8.6 supposed to be out? Shouldn't this issue be closed once v3.8.6 is out and confirmed as closed?

3.8.6 should be out today and we will re-open the issue if its not resolved. Github auto closes it when a PR linked to the issue is closed.

**Comment by turribeach** [comment]
Just downloaded v3.8.6 and tested it and the issue is still there. Can you please reopen the issue?

**Comment by Mattish** [comment]
This issue is not resolved v3.8.6, iOS 15.0 iPhone SE. There is no difference in behaviour from previous versions.

Having incorrect antenna information now negatively impacts the helium network, please remove all animations for these modals or look to correct this issue asap. 

@tyler-whitman

**Comment by tyler-whitman** [comment]
@Mattish @turribeach would either of you be able to send me a friend request on discord (tyler.helium#0588) so I can reach out with a beta build of the app to test some fixes for this issue?

**Comment by jbuecker** [comment]
I am sending you a friend request now

I am RandomPlanet on Discord



Jason Buecker
770.428.4205
 MacintoshConsultants.Com

Apple Consultants Network
Apple Certified Technical Coordinator (ACTC)

**Comment by tyler-whitman** [comment]
We have tracked it down to an iOS setting in Accessibility > Motion > Reduce Motion and enabling "Prefer Cross-Fade Transitions" is causing the bug. We have a fix coming in the next release which will be 3.9.0. If you want to resolve it as soon as possible, disabling "Prefer Cross-Fade Transitions" temporarily will work.

**Comment by cokes518** [comment]
The fix for this is now available on 3.9.0. The root cause was an accessibility option to reduce motion.
